module.exports = [
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    },
    {
        "img":require("../images/pages/BEDS/1.jpg"),
        "title":"床-1",
        "price":"2354"
    }
]